/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormularioCliente: typeof import('./components/FormularioCliente.vue')['default']
    FormularioImovel: typeof import('./components/FormularioImovel.vue')['default']
    FormularioLeilao: typeof import('./components/FormularioLeilao.vue')['default']
    FormularioLogin: typeof import('./components/FormularioLogin.vue')['default']
    FormularioUsuario: typeof import('./components/FormularioUsuario.vue')['default']
    FormularioVeiculo: typeof import('./components/FormularioVeiculo.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Leiloes: typeof import('./components/Leiloes.vue')['default']
    'Leilões': typeof import('./components/Leilões.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teste: typeof import('./components/teste.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
  }
}
